# Site settings
title: By Dre.co | All the products you knew we were coming up with.
email: stevenmaguire@gmail.com
description: > 
  Explore the bleeding edge of consumer technology from the only family of products that matter.
baseurl: "" 
url: "http://www.bydre.co"

# Build settings
markdown: kramdown

exclude:
    - bower_components
    - node_modules
    - Rakefile
    - Gemfile
    - Gemfile.lock
